sudo: required
services:
  - docker

before_install:
  - docker build -t justintillman/docker-react -f Dockerfile.dev .

script:
  - docker run justintillman/docker-react npm run test -- --coverage
